"""adiciona models de gestao

Revision ID: a041aeb76664
Revises: d6b767f2e139
Create Date: 2025-12-30 11:37:46.109870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a041aeb76664'
down_revision = 'd6b767f2e139'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo_pessoa', sa.String(length=1), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cpf_cnpj'), 'clientes', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CAMINHAO', 'RETROESCAVADEIRA', 'TRATOR', 'ESCAVADEIRA', 'PA_CARREGADEIRA', 'ROLO_COMPACTADOR', 'OUTRO', name='tipoequipamento'), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('identificador', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('valor_aquisicao', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('hodometro_inicial', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hodometro_atual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamentos_id'), 'equipamentos', ['id'], unique=False)
    op.create_index(op.f('ix_equipamentos_identificador'), 'equipamentos', ['identificador'], unique=True)
    op.create_index(op.f('ix_equipamentos_placa'), 'equipamentos', ['placa'], unique=True)
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('cnh', sa.String(length=20), nullable=False),
    sa.Column('categoria_cnh', sa.String(length=2), nullable=False),
    sa.Column('validade_cnh', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motoristas_cpf'), 'motoristas', ['cpf'], unique=True)
    op.create_index(op.f('ix_motoristas_id'), 'motoristas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('contratos_locacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_contrato', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim_prevista', sa.Date(), nullable=True),
    sa.Column('data_fim_real', sa.Date(), nullable=True),
    sa.Column('tipo_cobranca', sa.Enum('DIARIA', 'MENSAL', 'HORA', 'FECHADO', name='tipocobranca'), nullable=False),
    sa.Column('valor_cobranca', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_caucao', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'FINALIZADO', 'CANCELADO', name='statuscontrato'), nullable=False),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_locacao_id'), 'contratos_locacao', ['id'], unique=False)
    op.create_index(op.f('ix_contratos_locacao_numero_contrato'), 'contratos_locacao', ['numero_contrato'], unique=True)
    op.create_table('abastecimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('data_abastecimento', sa.Date(), nullable=False),
    sa.Column('tipo_combustivel', sa.Enum('DIESEL', 'GASOLINA', 'ETANOL', 'GNV', 'OUTRO', name='tipocombustivel'), nullable=False),
    sa.Column('litros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_litro', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('km_hodometro', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('posto', sa.String(length=255), nullable=True),
    sa.Column('numero_nota', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('lancamento_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abastecimentos_data_abastecimento'), 'abastecimentos', ['data_abastecimento'], unique=False)
    op.create_index(op.f('ix_abastecimentos_id'), 'abastecimentos', ['id'], unique=False)
    op.create_table('manutencoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PREVENTIVA', 'CORRETIVA', 'PREDITIVA', name='tipomanutencao'), nullable=False),
    sa.Column('status', sa.Enum('AGENDADA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='statusmanutencao'), nullable=False),
    sa.Column('data_agendada', sa.Date(), nullable=True),
    sa.Column('data_realizada', sa.Date(), nullable=True),
    sa.Column('km_hodometro', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('oficina', sa.String(length=255), nullable=True),
    sa.Column('mecanico', sa.String(length=255), nullable=True),
    sa.Column('valor_mao_obra', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_pecas', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('numero_nota', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('lancamento_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manutencoes_data_agendada'), 'manutencoes', ['data_agendada'], unique=False)
    op.create_index(op.f('ix_manutencoes_id'), 'manutencoes', ['id'], unique=False)
    op.create_table('viagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('data_viagem', sa.Date(), nullable=False),
    sa.Column('hora_saida', sa.Time(), nullable=True),
    sa.Column('hora_chegada', sa.Time(), nullable=True),
    sa.Column('origem', sa.String(length=255), nullable=False),
    sa.Column('destino', sa.String(length=255), nullable=False),
    sa.Column('km_inicial', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('km_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('km_percorrido', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('lancamento_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viagens_data_viagem'), 'viagens', ['data_viagem'], unique=False)
    op.create_index(op.f('ix_viagens_id'), 'viagens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viagens_id'), table_name='viagens')
    op.drop_index(op.f('ix_viagens_data_viagem'), table_name='viagens')
    op.drop_table('viagens')
    op.drop_index(op.f('ix_manutencoes_id'), table_name='manutencoes')
    op.drop_index(op.f('ix_manutencoes_data_agendada'), table_name='manutencoes')
    op.drop_table('manutencoes')
    op.drop_index(op.f('ix_abastecimentos_id'), table_name='abastecimentos')
    op.drop_index(op.f('ix_abastecimentos_data_abastecimento'), table_name='abastecimentos')
    op.drop_table('abastecimentos')
    op.drop_index(op.f('ix_contratos_locacao_numero_contrato'), table_name='contratos_locacao')
    op.drop_index(op.f('ix_contratos_locacao_id'), table_name='contratos_locacao')
    op.drop_table('contratos_locacao')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_motoristas_id'), table_name='motoristas')
    op.drop_index(op.f('ix_motoristas_cpf'), table_name='motoristas')
    op.drop_table('motoristas')
    op.drop_index(op.f('ix_equipamentos_placa'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_identificador'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_id'), table_name='equipamentos')
    op.drop_table('equipamentos')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf_cnpj'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
