"""initial migration

Revision ID: d6b767f2e139
Revises: 
Create Date: 2025-12-30 11:29:55.146459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b767f2e139'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centros_custo_codigo'), 'centros_custo', ['codigo'], unique=True)
    op.create_index(op.f('ix_centros_custo_id'), 'centros_custo', ['id'], unique=False)
    op.create_table('historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historicos_codigo'), 'historicos', ['codigo'], unique=True)
    op.create_index(op.f('ix_historicos_id'), 'historicos', ['id'], unique=False)
    op.create_table('plano_contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('ATIVO', 'PASSIVO', 'PATRIMONIO_LIQUIDO', 'RECEITA', 'DESPESA', name='tipoconta'), nullable=False),
    sa.Column('natureza', sa.Enum('DEVEDORA', 'CREDORA', name='naturezaconta'), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('conta_pai_id', sa.Integer(), nullable=True),
    sa.Column('aceita_lancamento', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conta_pai_id'], ['plano_contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plano_contas_codigo'), 'plano_contas', ['codigo'], unique=True)
    op.create_index(op.f('ix_plano_contas_id'), 'plano_contas', ['id'], unique=False)
    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_lancamento', sa.Date(), nullable=False),
    sa.Column('numero_lote', sa.String(length=20), nullable=True),
    sa.Column('historico_id', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=500), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['historico_id'], ['historicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lancamentos_data_lancamento'), 'lancamentos', ['data_lancamento'], unique=False)
    op.create_index(op.f('ix_lancamentos_id'), 'lancamentos', ['id'], unique=False)
    op.create_index(op.f('ix_lancamentos_numero_lote'), 'lancamentos', ['numero_lote'], unique=False)
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lancamento_id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('DEBITO', 'CREDITO', name='tipopartida'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('centro_custo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['plano_contas.id'], ),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidas_id'), 'partidas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partidas_id'), table_name='partidas')
    op.drop_table('partidas')
    op.drop_index(op.f('ix_lancamentos_numero_lote'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_id'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_data_lancamento'), table_name='lancamentos')
    op.drop_table('lancamentos')
    op.drop_index(op.f('ix_plano_contas_id'), table_name='plano_contas')
    op.drop_index(op.f('ix_plano_contas_codigo'), table_name='plano_contas')
    op.drop_table('plano_contas')
    op.drop_index(op.f('ix_historicos_id'), table_name='historicos')
    op.drop_index(op.f('ix_historicos_codigo'), table_name='historicos')
    op.drop_table('historicos')
    op.drop_index(op.f('ix_centros_custo_id'), table_name='centros_custo')
    op.drop_index(op.f('ix_centros_custo_codigo'), table_name='centros_custo')
    op.drop_table('centros_custo')
    # ### end Alembic commands ###
